import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatCurrency, formatDate } from './dateHelpers';

const BRAND_COLOR = [99, 102, 241]; // primary-500 indigo

const addHeader = (doc, title, shopName, dateRange) => {
  // Header bar
  doc.setFillColor(...BRAND_COLOR);
  doc.rect(0, 0, 210, 28, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Katha Book', 14, 12);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(shopName || 'Digital Due Book', 14, 20);

  doc.setFontSize(10);
  doc.text(title, 210 - 14, 12, { align: 'right' });
  if (dateRange) doc.text(dateRange, 210 - 14, 20, { align: 'right' });

  doc.setTextColor(0, 0, 0);
  return 36;
};

export const generateBillPDF = (bill, payments, shopInfo) => {
  const doc = new jsPDF();
  let y = addHeader(doc, 'Bill', shopInfo?.shopName, formatDate(bill.createdAt));

  // Customer info
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Customer Details', 14, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const customer = bill.customerId;
  doc.text([
    `Name: ${customer?.name || '—'}`,
    `Phone: ${customer?.phone || '—'}`,
    `Shop: ${customer?.shopName || '—'}`,
  ], 14, y + 6);

  // Bill info (right side)
  doc.setFont('helvetica', 'bold');
  doc.text(`Bill No: ${bill.billNumber}`, 210 - 14, y, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.text([
    `Date: ${formatDate(bill.createdAt)}`,
    `Due Date: ${formatDate(bill.dueDate)}`,
    `Status: ${bill.status.toUpperCase()}`,
  ], 210 - 14, y + 6, { align: 'right' });

  y += 32;

  // Items table
  autoTable(doc, {
    startY: y,
    head: [['#', 'Product', 'Qty', 'Unit', 'Price', 'Subtotal']],
    body: (bill.items || []).map((item, i) => [
      i + 1,
      item.name,
      item.quantity,
      item.unit || 'pcs',
      formatCurrency(item.price),
      formatCurrency(item.subtotal),
    ]),
    styles: { fontSize: 9 },
    headStyles: { fillColor: BRAND_COLOR, textColor: 255 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { left: 14, right: 14 },
  });

  y = doc.lastAutoTable.finalY + 8;

  // Totals
  const totalsData = [
    ['Total Amount', formatCurrency(bill.totalAmount)],
    ['Amount Paid', formatCurrency(bill.paidAmount)],
    ['Due Amount', formatCurrency(bill.dueAmount)],
  ];
  if (bill.accruedPenalty > 0) {
    totalsData.push(['Penalty', formatCurrency(bill.accruedPenalty)]);
    totalsData.push(['Total Outstanding', formatCurrency(bill.dueAmount + bill.accruedPenalty)]);
  }

  autoTable(doc, {
    startY: y,
    body: totalsData,
    styles: { fontSize: 10, halign: 'right' },
    columnStyles: { 0: { fontStyle: 'bold', halign: 'left' } },
    margin: { left: 100, right: 14 },
    tableWidth: 96,
  });

  y = doc.lastAutoTable.finalY + 12;

  // Payment history
  if (payments?.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('Payment History', 14, y);
    y += 4;

    autoTable(doc, {
      startY: y,
      head: [['Date', 'Amount Paid', 'Method', 'Remaining Due']],
      body: payments.map((p) => [
        formatDate(p.paymentDate),
        formatCurrency(p.amountPaid),
        p.paymentMethod || 'Cash',
        formatCurrency(p.remainingDue),
      ]),
      styles: { fontSize: 9 },
      headStyles: { fillColor: [100, 116, 139], textColor: 255 },
      margin: { left: 14, right: 14 },
    });
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Generated by Katha Book | Page ${i} of ${pageCount}`,
      105, 290, { align: 'center' }
    );
  }

  doc.save(`Bill-${bill.billNumber}.pdf`);
};

export const generateReportPDF = (report, shopInfo) => {
  const doc = new jsPDF();
  const typeLabel = report.type ? report.type.charAt(0).toUpperCase() + report.type.slice(1) : 'Custom';
  const dateRange = `${formatDate(report.startDate)} - ${formatDate(report.endDate)}`;
  let y = addHeader(doc, `${typeLabel} Report`, shopInfo?.shopName, dateRange);

  // Summary cards
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', 14, y);
  y += 6;

  autoTable(doc, {
    startY: y,
    body: [
      ['Total Sales', formatCurrency(report.summary?.totalSales)],
      ['Total Collected', formatCurrency(report.summary?.totalCollected)],
      ['Total Pending', formatCurrency(report.summary?.totalPending)],
      ['Total Bills', report.summary?.totalBills || 0],
    ],
    styles: { fontSize: 10 },
    columnStyles: { 0: { fontStyle: 'bold' } },
    margin: { left: 14, right: 14 },
    tableWidth: 100,
  });

  y = doc.lastAutoTable.finalY + 12;

  // Bills in period
  if (report.bills?.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('Bills', 14, y);
    y += 4;

    autoTable(doc, {
      startY: y,
      head: [['Bill No', 'Customer', 'Date', 'Total', 'Paid', 'Due', 'Status']],
      body: report.bills.map((b) => [
        b.billNumber,
        b.customerId?.name || '—',
        formatDate(b.createdAt),
        formatCurrency(b.totalAmount),
        formatCurrency(b.paidAmount),
        formatCurrency(b.dueAmount),
        b.status,
      ]),
      styles: { fontSize: 8 },
      headStyles: { fillColor: BRAND_COLOR, textColor: 255 },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      margin: { left: 14, right: 14 },
    });
    y = doc.lastAutoTable.finalY + 12;
  }

  // Pending dues
  if (report.pendingDues?.length > 0) {
    if (y > 240) { doc.addPage(); y = 20; }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('Pending Dues', 14, y);
    y += 4;

    autoTable(doc, {
      startY: y,
      head: [['Customer', 'Bill No', 'Due Date', 'Due Amount', 'Penalty', 'Total Outstanding']],
      body: report.pendingDues.map((b) => [
        b.customerId?.name || '—',
        b.billNumber,
        formatDate(b.dueDate),
        formatCurrency(b.dueAmount),
        formatCurrency(b.accruedPenalty || 0),
        formatCurrency(b.totalOutstanding || b.dueAmount),
      ]),
      styles: { fontSize: 8 },
      headStyles: { fillColor: [239, 68, 68], textColor: 255 },
      margin: { left: 14, right: 14 },
    });
  }

  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Generated by Katha Book | Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
  }

  doc.save(`Katha-Book-${typeLabel}-Report.pdf`);
};
